FROM tomcat:8.0.24-jre8
ADD war-demo-catalog/target/catalog.war /usr/local/tomcat/webapps/
ADD war-demo-customer/target/customer.war /usr/local/tomcat/webapps/
ADD war-demo-order/target/order.war /usr/local/tomcat/webapps/
